apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: cm9vdDEyMw==  # "root123"
  user: dXNlcjEyMw==          # "user123"
  password: cGFzczEyMw==      # "pass123"
